### ISSUE TITLE
Api Wizzard World Issue Service Unavailable

### ISSUE THREAD

**Issue by Nadaco** [MossPiglets/WizardWorldAPI#28]
Hey, I'm not sure if it's the write place to write this so sorry in advance.

I have some problems to access datas with this API. So I try it with your swagger, but the same issue appears. Maybe an issue with the wiki? I don't know.
I use your API for a university project for learn javascript, so thanks you for your good work.
 
![image](https://user-images.githubusercontent.com/80447530/160478304-691dc48d-27a4-4991-8733-94310811c440.png)

**Comment by Morasiu** [comment]
Actually API is so popular we exceeded free quota or Heroku. It should reset at the start of the month, but I will try to fix it sooner.

**Comment by Morasiu** [comment]
Okay. It should work now. Happy codding!
